app_module = "textual_cmdorc.cmdorc_app"
app_class = "CmdorcApp"
module_path = "/workspaces/textual-cmdorc/src/textual_cmdorc"

[[step]]
type = "capture"

[[step]] # Run first command (Lint)
type = "press"
keys = ["1"]

[[step]]
type = "delay"
seconds = 0.5

[[step]]   # Open Lint settings
type = "press"
keys = ["tab", "s"]

[[step]]
type = "delay"
seconds = 1.0

[[step]]
type = "capture"

[[step]] # Exit Lint settings display
type = "press"
keys = ["q"]

[[step]]
type = "delay"
seconds = 1.0

[[step]]
type = "capture"


[[step]] # Run first command (Lint)
type = "press"
keys = ["1"]

[[step]]
type = "delay"
seconds = 1.0

[[step]]
type = "capture"